### ISSUE TITLE
Traduzir o Meteor JS

### ISSUE THREAD

**Issue by leonardo403** [ericdouglas/traduz-ai#39]
Oi Eric,

O que você acha de começarmos a traduzir o Meteor js (https://www.meteor.com/) ?

**Comment by bdadev** [comment]
Seria mais uma grande tradução de sucesso. Um complemento significativo para essa lista de traduções que, ao meu ver, tem uma fatia bem grande no desenvolvimento web, em se tratando de fazer com que a informação privilegiada lá de fora seja compreendida em sua grande maioria aqui.

Parabéns a todos os envolvidos pela ótima iniciativa!

**Comment by lucasfcosta** [comment]
Gostei da ideia, acho até que vou aprender bastante enquanto faço a tradução.
Traduziremos a documentação, todo o conteúdo, qual será o escopo?

Estou a disposição pra contribuir!

**Comment by leonardo403** [comment]
Bom dia galera,

Eric preciso saber se vamos criar um checklist antes de começar a tradução
? Listando quais partes serão traduzidas ou cada um pega uma parte ?

Abs,

2015-01-15 8:59 GMT-02:00 Lucas Fernandes da Costa <notifications@github.com
>:

> Gostei da ideia, acho até que vou aprender bastante enquanto faço a
> tradução.
> Traduziremos a documentação, todo o conteúdo, qual será o escopo?
>
> Estou a disposição pra contribuir!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ericdouglas/traduz-ai/issues/39#issuecomment-70069785>
> .
>



-- 
*Leonardo Lima*
*Web developer Jr.*

Fone:  *(051) 8336-5081*
Github: https://github.com/leonardo403
Google+: https://plus.google.com/u/0/+LeonardoLimawebdev/
About.me: http://about.me/leonardolima
Twitter: https://twitter.com/Leonardo403Br

**Comment by ericdouglas** [comment]
Galera, o @guilhermedecampo havia começado a tradução da doc ano passado [aqui](https://github.com/MeteorBrasil). Já tinha conversado com ele para ajudá-lo nisso.

Eu animo em contribuir, podemos ver o que fazer, e divulgar também no grupo Meteor Brasil no facebook para ver quem mais topa ajudar.

**Comment by leonardo403** [comment]
O galera o projeto do Meteor Brasil esta muito legal. Vamos terminar a
tradução então, pois assim vamos aprendendo mais sobre o
Javascript,Framework e Inglês.
O que vocês acham ?

2015-01-15 9:45 GMT-02:00 Eric Douglas <notifications@github.com>:

> Galera, o @guilhermedecampo <https://github.com/guilhermedecampo> havia
> começado a tradução da doc ano passado aqui
> <https://github.com/MeteorBrasil>. Já tinha conversado com ele para
> ajudá-lo nisso.
>
> Eu animo em contribuir, podemos ver o que fazer, e divulgar também no
> grupo Meteor Brasil no facebook para ver quem mais topa ajudar.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ericdouglas/traduz-ai/issues/39#issuecomment-70074533>
> .
>



-- 
*Leonardo Lima*
*Web developer Jr.*

Fone:  *(051) 8336-5081*
Github: https://github.com/leonardo403
Google+: https://plus.google.com/u/0/+LeonardoLimawebdev/
About.me: http://about.me/leonardolima
Twitter: https://twitter.com/Leonardo403Br

**Comment by guilhermedecampo** [comment]
Uma boa galera! =)

**Comment by danilovaz** [comment]
alguma novidade sobre essa tradução do Meteor.

**Comment by guilhermedecampo** [comment]
Se quiser começar @danilovaz manda um pull request aqui: https://github.com/MeteorBrasil/meteor-docsbr

**Comment by ericdouglas** [comment]
@danilovaz como a tradução de uma doc é um projeto grande, é melhor ser feito com um repositório próprio, e o melhor lugar é onde o @guilhermedecampo indicou mesmo!

:smile:

**Comment by danilovaz** [comment]
@guilhermedecampo o que especificamente preciso enviar nesse PR? não entendi bem essa parte :smile: 

@ericdouglas ah entendi, legal! vamos ver no que consigo ajudar =) valeu!

**Comment by ericdouglas** [comment]
@danilovaz :+1:

**Comment by leonardo403** [comment]
Hello galera,

Vamos começar a tradução ?

On Mon, Feb 9, 2015 at 11:04 PM, Eric Douglas <notifications@github.com>
wrote:

> @danilovaz <https://github.com/danilovaz> [image: :+1:]
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ericdouglas/traduz-ai/issues/39#issuecomment-73624977>
> .
>



-- 
*Leonardo Lima*
*Web developer Jr.*

Fone:  *(051) 8336-5081*
Github: https://github.com/leonardo403
Google+: https://plus.google.com/u/0/+LeonardoLimawebdev/
About.me: http://about.me/leonardolima
Twitter: https://twitter.com/Leonardo403Br

**Comment by leonardo403** [comment]
Aqui vocês conseguem ver o que está falatando ser traduzido.
http://docsbr.meteor.com/

On Tue, Feb 10, 2015 at 1:48 PM, Leonardo Lima <leonardo403@gmail.com>
wrote:

> Hello galera,
>
> Vamos começar a tradução ?
>
> On Mon, Feb 9, 2015 at 11:04 PM, Eric Douglas <notifications@github.com>
> wrote:
>
>> @danilovaz <https://github.com/danilovaz> [image: :+1:]
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ericdouglas/traduz-ai/issues/39#issuecomment-73624977>
>> .
>>
>
>
>
> --
> *Leonardo Lima*
> *Web developer Jr.*
>
> Fone:  *(051) 8336-5081*
> Github: https://github.com/leonardo403
> Google+: https://plus.google.com/u/0/+LeonardoLimawebdev/
> About.me: http://about.me/leonardolima
> Twitter: https://twitter.com/Leonardo403Br
>
>
>


-- 
*Leonardo Lima*
*Web developer Jr.*

Fone:  *(051) 8336-5081*
Github: https://github.com/leonardo403
Google+: https://plus.google.com/u/0/+LeonardoLimawebdev/
About.me: http://about.me/leonardolima
Twitter: https://twitter.com/Leonardo403Br

**Comment by guilhermedecampo** [comment]
galera estou dando uma geral e modificando legacy. Amanhã a noite fica pronto =)

**Comment by danilovaz** [comment]
show, valeu @guilhermedecampo :smile:

**Comment by guilhermedecampo** [comment]
Eai galera mals ai pelo atraso.
 Tive um imprevisto familiar mas está tudo certo agora!

https://github.com/MeteorBrasil/meteor-docsbr.

**Comment by ericdouglas** [comment]
Show @guilhermedecampo !

Fechando essa issue para as discussões agora serem feitas lá no repo da tradução :smile:
