### ISSUE TITLE
atualização de tutorial

### ISSUE THREAD

**Issue by alexaleluia12** [ericdouglas/traduz-ai#44]
Eu sofrei um pouco para seguir 002-simples-guia-nodejs-jade-express-mongodb.
Seria muito bom esse tutorial fosse atualizado para a nova versão do 'Express' atualmente 4.11.1
Eu acho que mudou muito desde a 3.4

**Comment by ericdouglas** [comment]
@alexaleluia12 como é uma tradução, fica inviável fazer uma adaptação.

É melhor pegarmos um artigo novo para traduzir, ou criar um artigo mesmo.

Se tiver sugestões de artigos, pode deixar aqui! Abraço!

**Comment by ericdouglas** [comment]
Atualizado!
