### ISSUE TITLE
Finalizar tradução do Handlebars.

### ISSUE THREAD

**Issue by thulioph** [ericdouglas/traduz-ai#47]
@ericdouglas tava querendo trabalhar na conclusão nessa tradução do [Handlebars](https://github.com/ericdouglas/traduz-ai/blob/master/handlebars/001-aprenda-tudo-sobre-handlebars.md) e queria saber se você tem algum padrão para novas contribuições.

Posso seguir o padrão:
- Realizar o fork.
- Fazer as modificações.
- Submeter um pr.

Abraço :smile:

**Comment by danilovaz** [comment]
@thulioph se precisar de ajuda, chama aí =)

**Comment by ericdouglas** [comment]
Pode ser dessa forma sim @thulioph !

@danilovaz , vocês podem dividir os tópicos restantes.

Se quiserem usar essa issue para isso, fiquem à vontade!

:smile:

**Comment by danilovaz** [comment]
@ericdouglas boa! :smiley: 

@thulioph o que acha? podemos dividir as tarefas e somar forças =)

**Comment by thulioph** [comment]
Foi mal a demora @danilovaz, ja é então. Vamos manter o contato nessa _issue_ e trabalhar nessa juntos!

**Comment by thulioph** [comment]
Temos 5 tópicos para serem finalizados, poderíamos dividir:

#### @thulioph
- Aprenda a sintaxe Handlebars.js
- Auxiliares Handlebars.js embutidos (condicionais e loops)

#### @danilovaz 
- Auxiliares Personalizados Handlebars.js
- 4 maneiras de carregar/adicionar templates

E quem finalizar primeiro pega:
-  Handlebars.js com Backbone.js, jQuery, Ember.js e Meteor.js

O que você acha? Não segui nenhum critério pra escolha mas aceito sugestões :+1:

**Comment by danilovaz** [comment]
Opa! Então, por mim pode fechar nesses tópicos. Trabalharemos no mesmo fork?

**Comment by thulioph** [comment]
Acho melhor não, você faz um e eu faço outro, no final a gente ajeita os conflitos que não serão muitos e manda o pr, o que você acha @danilovaz?

**Comment by danilovaz** [comment]
Legal @thulioph podemos seguir assim então. Vou forkar aqui e mãos à obra rs =) quando eu terminar eu te aviso por aqui para discutir os próximos passos e o PR

**Comment by thulioph** [comment]
Formô!

**Comment by thulioph** [comment]
@danilovaz iai, alguma novidade? Acabei de mandar um [pull request](https://github.com/ericdouglas/traduz-ai/pull/48) com as traduções, posso tocar o tópico final? Como tá o seu desenvolvimento?

**Comment by thulioph** [comment]
@danilovaz vai continuar ainda man? Tá precisando de ajuda ou posso tocar o restante?

**Comment by thulioph** [comment]
@ericdouglas desculpa a demora pra voltar a tradução, mas mandei um [pull request](https://github.com/ericdouglas/traduz-ai/pull/53), se tiver faltando algo é só falar :)

**Comment by ericdouglas** [comment]
Muito obrigado @thulioph ! Falta você colocar seu nome no início lá em tradução :wink:

**Comment by thulioph** [comment]
Feito @ericdouglas, mandei outro [pull request](https://github.com/ericdouglas/traduz-ai/pull/54). :smile:
