### ISSUE TITLE
Dúvida: qual artigo traduzir?

### ISSUE THREAD

**Issue by fernandoguedes** [ericdouglas/traduz-ai#57]
Vi que na orientação que está no README.md, eu deveria ou procurar um arquivo pra tradução, ou, eu mesmo indicar um por aqui, como funciona, poderia esclarecer melhor? Gostaria de contribuir com as traduções.

Link do artigo original que eu desejo traduzir, já fiz o clone do projeto e já iniciei a tradução, poderia dar melhores orientações sobre?

http://tutorialzine.com/2015/06/making-your-first-html5-game-with-phaser/

**Comment by ericdouglas** [comment]
@fernandoguedes você já fez o mais difícil hehe =P

Só forkar o projeto, criar o arquivo .md de tradução na respectiva pasta (de acordo com o assunto), atualizar o README linkando para o arquivo traduzido e enviar o PR!

:smile: 

Se tiver mais dúvidas, só perguntar!

**Comment by santosluiz** [comment]
Poxa, tive a mesma dúvida rsrs

Obrigado @ericdouglas! :P
