### ISSUE TITLE
Dúvida: Pull Request apenas de artigos totalmente traduzidos?

### ISSUE THREAD

**Issue by gutierri** [ericdouglas/traduz-ai#64]
Como funcionaria isso? Posso mandar um arquivo "semi traduzido"? Não encontrei este tipo de informação no README.
:)

**Comment by ericdouglas** [comment]
@gutierri pode mandar semi traduzido sim, e ir complementando com pequenos commits :)

**Comment by gutierri** [comment]
@ericdouglas Perfeito.
