### ISSUE TITLE
Tradução de Livro

### ISSUE THREAD

**Issue by reginaldojunior** [ericdouglas/traduz-ai#67]
@ericdouglas Muito legal o projeto, parabéns.

Comecei um a algum tempo atrás parecido, mas é para um mini livro do Cal Evans o "Wisdom of the Elephant" existe pouquíssimos exemplares dele e foi distribuído de forma gratuita e estou escrevendo a tradução, olhe neste repositório https://github.com/reginaldojunior/wisdom-of-the-elephant minha ideia é traduzir para varias línguas também.

Será que tem como referenciar o meu repositório no seu para aumentamos o numero de pessoas com acesso a este livro e aumentar a comunidade em traduzi-lo?

**Comment by ericdouglas** [comment]
@reginaldojunior parabéns por iniciar este projeto! Já adicionei o link dele no readme :smile:

**Comment by reginaldojunior** [comment]
@ericdouglas Opa Obrigado! :dancer:
